POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYwZTJkMGVhNzM1YzM1NDc4MDQ4ZWQzMyIsImlhdCI6MTYyNjI1NDI2N30.W_oOIgvZcKsCeAKqfZHaKi-AalErJ0Hy-NWslFwsf3s

{
    "title": "Testing3",
    "author": "Chris Topalis",
    "url": "www.willExistSoon.com",
    "likes": 0
}